name: PMReddit
main: skyss0fly\PMReddit\Main
version: 1.0
api: 5.0.0
author: skyss0fly
description: A simple reddit plugin
permissions:
  PMReddit.use:
    default: op
commands:
  reeit:
    description: use this to access reddit
    permission: PMReddit.use
    default: false
  
