name: PMReddit
version: 0.0.1
api: 5.0.0
author: skyss0fly
description: Access reddit without closing minecraft
permissions:
 PMReddit.use:
  default: false

commands:
 reddit:
 permission: PMReddit.use
 default: false
 description: Use this to access reddit
